name: Java CI
on: [ push ]

jobs:
  build:
    environment: main
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - shell: bash
        env:
          host: ${{ secrets.FTP_HOST }}
          pw: ${{ secrets.FTP_PW }}
          user: ${{ secrets.FTP_USER }}
        run: |
          cd ./src/main/java/xyz/reisminer/chtop
          wget --mirror --continue --no-host-directories --user=$user --password=$pw ftp://$host/httpdocs/secret/Token.java
          cd ../../../../../../
      - name: Build with Gradle
        run: ./gradlew shadowjar
      - name: Upload Built Jar To Github
        uses: actions/upload-artifact@v2
        with:
          name: CHTOP Jar
          path: ./build/libs/CustomCommands-1.0-all.jar
      - shell: bash
        env:
          host: ${{ secrets.PI_SSH_HOST }}
          port: ${{ secrets.PI_SSH_PORT }}
          pw: ${{ secrets.PI_SSH_PW }}
          user: ${{ secrets.PI_SSH_USER }}
        run: |
          sshpass -p "$pw" scp ./build/libs/CustomCommands-1.0-all.jar $user@$host:/home/$user/Desktop/Bots -p $port


